version: '3'
services:
  my-backend:
    image: meruem1erdunom/myrepo:back
    ports:
      - "8080:8080" 
    environment:
      - CURRENT_ENVIRONMENT=development
    volumes:
      - ./backend_data:/app/logs # Mount a local directory to persist backend data

  my-frontend:
    image: meruem1erdunom/myrepo:front
    ports:
      - "8081:80"
    environment:
      - WS_BACK_URL=http://172.18.0.3:5000/
